/*
 * This file was automatically generated by EvoSuite
 * Tue Apr 02 14:57:11 GMT 2019
 */

package org.ow2.authzforce.core.pdp.impl;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import java.util.Stack;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;
import org.ow2.authzforce.core.pdp.impl.SchemaHandler;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class SchemaHandler_ESTest extends SchemaHandler_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      Stack<String> stack0 = new Stack<String>();
      stack0.push("");
      // Undeclared exception!
      SchemaHandler.createSchema(stack0, "");
  }
}
